// <auto-generated />
using System;
using LMS.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS.DAL.Migrations
{
    [DbContext(typeof(LMSDbContext))]
    [Migration("20250328143704_m4")]
    partial class m4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMS.DAL.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActivationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActivationUserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedUserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertedUserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TotalCopies")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("LMS.DAL.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActivationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActivationUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertedUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Books that contain stories created from the imagination.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Books based on real facts and events.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Books related to scientific principles, experiments, and discoveries.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Science"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Books covering mathematical theories, problems, and equations.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Books that discuss past events and historical occurrences.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "History"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Books about the lives of individuals, either famous or historical.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Books considered to have artistic value, including poetry, novels, and drama.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Literature"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Books that explore fundamental questions about existence, knowledge, and ethics.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Philosophy"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Books related to human behavior, emotions, and cognitive functions.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Psychology"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Books that provide advice or strategies for improving life and personal growth.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Self-Help"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Books that focus on various forms of art, including visual arts, sculpture, and performance.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Art"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Books that discuss musical theory, history, and performance techniques.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Books focused on physical well-being, exercise, and mental health.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Health & Fitness"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Books providing recipes and cooking techniques.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Books that explore destinations, cultures, and experiences in different parts of the world.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Books intended for young readers, including stories and educational books.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Children's Books"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Books containing magical or fantastical elements set in imaginary worlds.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Books set in the future or in space, often incorporating advanced technology or extraterrestrial life.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Books centered around solving a crime or uncovering secrets.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Books designed to keep the reader on edge with suspense and tension.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Books designed to evoke fear or unease in the reader.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Books containing poems, written in verse.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Poetry"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Books focused on religious studies, scriptures, and beliefs.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Religion"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Books that explore personal growth and the search for meaning beyond the material world.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Spirituality"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Books that explore political theory, history, and analysis.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Politics"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Books about the production, distribution, and consumption of goods and services.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Economics"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Books on management, entrepreneurship, and business strategies.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Business"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Books covering advancements in technology, including programming, artificial intelligence, and gadgets.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Books on engineering principles, innovations, and applications.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Books about legal studies, statutes, and legal principles.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Law"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Books about the art and techniques of photography.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Photography"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Books on the design and construction of buildings and other structures.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Architecture"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Books about various sports, athletes, and sporting events.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Books focused on ecology, nature conservation, and environmental science.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Environment"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Books about cities, urban planning, and metropolitan life.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Urban Studies"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Books related to financial markets, investment strategies, and economic theory.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Economics & Finance"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Books offering advice for raising children and family dynamics.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Parenting"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Books on educational methods, theories, and teaching practices.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Books consisting of illustrated stories in a comic strip format.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Comic Books"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Books that combine illustrations with narrative storytelling, typically in a longer form.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Graphic Novels"
                        },
                        new
                        {
                            Id = 41,
                            Description = "Books covering sociology, anthropology, and other social studies disciplines.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Social Sciences"
                        },
                        new
                        {
                            Id = 42,
                            Description = "Books related to the scientific study of language and its structure.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Linguistics"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Books about physical geography, the study of places and environments.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Geography"
                        },
                        new
                        {
                            Id = 44,
                            Description = "Books about space exploration, the universe, stars, and planets.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Space & Astronomy"
                        },
                        new
                        {
                            Id = 45,
                            Description = "Books that incorporate mathematical themes or problems in their stories.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mathematical Fiction"
                        },
                        new
                        {
                            Id = 46,
                            Description = "Books about the history and collection of valuable items.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Antiques & Collectibles"
                        },
                        new
                        {
                            Id = 47,
                            Description = "Books about various crafts, from knitting to woodworking.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Crafts & Hobbies"
                        },
                        new
                        {
                            Id = 48,
                            Description = "Books about planting, cultivating, and maintaining gardens.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gardening"
                        },
                        new
                        {
                            Id = 49,
                            Description = "Books that focus on managing personal wealth, budgeting, and investing.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Personal Finance"
                        },
                        new
                        {
                            Id = 50,
                            Description = "Books that explore real-life criminal cases and investigations.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "True Crime"
                        });
                });

            modelBuilder.Entity("LMS.DAL.Data.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateOnly(1896, 9, 1),
                            Description = "American novelist, best known for 'The Great Gatsby.'",
                            FullName = "F. Scott Fitzgerald"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateOnly(1926, 4, 20),
                            Description = "American author of 'To Kill a Mockingbird.'",
                            FullName = "Harper Lee"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateOnly(1976, 2, 24),
                            Description = "Israeli historian and author of 'Sapiens.'",
                            FullName = "Yuval Noah Harari"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateOnly(1986, 9, 27),
                            Description = "American memoirist, known for 'Educated.'",
                            FullName = "Tara Westover"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateOnly(1942, 1, 8),
                            Description = "English theoretical physicist, known for 'A Brief History of Time.'",
                            FullName = "Stephen Hawking"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateOnly(1941, 3, 26),
                            Description = "English evolutionary biologist, author of 'The Selfish Gene.'",
                            FullName = "Richard Dawkins"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateOnly(1959, 5, 13),
                            Description = "American mathematician, author of 'The Joy of x.'",
                            FullName = "Steven Strogatz"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateOnly(1838, 12, 20),
                            Description = "English schoolmaster and theologian, known for 'Flatland.'",
                            FullName = "Edwin A. Abbott"
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateOnly(1929, 6, 12),
                            Description = "Jewish diarist, known for 'The Diary of a Young Girl.'",
                            FullName = "Anne Frank"
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateOnly(1971, 8, 10),
                            Description = "British historian, author of 'The Silk Roads.'",
                            FullName = "Peter Frankopan"
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = new DateOnly(1952, 5, 20),
                            Description = "American author and biographer, known for 'Steve Jobs.'",
                            FullName = "Walter Isaacson"
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = new DateOnly(1925, 5, 19),
                            Description = "African American civil rights leader, co-author of 'The Autobiography of Malcolm X.'",
                            FullName = "Malcolm X"
                        },
                        new
                        {
                            Id = 13,
                            DateOfBirth = new DateOnly(1819, 8, 1),
                            Description = "American author, known for 'Moby-Dick.'",
                            FullName = "Herman Melville"
                        },
                        new
                        {
                            Id = 14,
                            DateOfBirth = new DateOnly(1775, 12, 16),
                            Description = "English novelist, best known for 'Pride and Prejudice.'",
                            FullName = "Jane Austen"
                        },
                        new
                        {
                            Id = 15,
                            DateOfBirth = new DateOnly(121, 4, 26),
                            Description = "Roman Emperor, known for 'Meditations.'",
                            FullName = "Marcus Aurelius"
                        },
                        new
                        {
                            Id = 16,
                            DateOfBirth = new DateOnly(427, 5, 21),
                            Description = "Ancient Greek philosopher, author of 'The Republic.'",
                            FullName = "Plato"
                        },
                        new
                        {
                            Id = 17,
                            DateOfBirth = new DateOnly(1934, 3, 5),
                            Description = "Israeli-American psychologist, author of 'Thinking, Fast and Slow.'",
                            FullName = "Daniel Kahneman"
                        },
                        new
                        {
                            Id = 18,
                            DateOfBirth = new DateOnly(1974, 4, 27),
                            Description = "American journalist, author of 'The Power of Habit.'",
                            FullName = "Charles Duhigg"
                        },
                        new
                        {
                            Id = 19,
                            DateOfBirth = new DateOnly(1986, 7, 22),
                            Description = "Author of 'Atomic Habits.'",
                            FullName = "James Clear"
                        },
                        new
                        {
                            Id = 20,
                            DateOfBirth = new DateOnly(1932, 10, 24),
                            Description = "American educator, author of 'The 7 Habits of Highly Effective People.'",
                            FullName = "Stephen R. Covey"
                        },
                        new
                        {
                            Id = 21,
                            DateOfBirth = new DateOnly(1909, 3, 20),
                            Description = "Austrian-born British art historian, known for 'The Story of Art.'",
                            FullName = "E.H. Gombrich"
                        },
                        new
                        {
                            Id = 22,
                            DateOfBirth = new DateOnly(1926, 11, 5),
                            Description = "British art critic and theorist, author of 'Ways of Seeing.'",
                            FullName = "John Berger"
                        },
                        new
                        {
                            Id = 23,
                            DateOfBirth = new DateOnly(1968, 11, 10),
                            Description = "American music critic, author of 'The Rest Is Noise.'",
                            FullName = "Alex Ross"
                        },
                        new
                        {
                            Id = 24,
                            DateOfBirth = new DateOnly(1952, 5, 14),
                            Description = "American musician and author of 'How Music Works.'",
                            FullName = "David Byrne"
                        },
                        new
                        {
                            Id = 25,
                            DateOfBirth = new DateOnly(1943, 7, 5),
                            Description = "Dutch-American psychiatrist, author of 'The Body Keeps the Score.'",
                            FullName = "Bessel van der Kolk"
                        },
                        new
                        {
                            Id = 26,
                            DateOfBirth = new DateOnly(1962, 6, 10),
                            Description = "American author, known for 'Born to Run.'",
                            FullName = "Christopher McDougall"
                        },
                        new
                        {
                            Id = 27,
                            DateOfBirth = new DateOnly(1877, 3, 15),
                            Description = "American author, known for 'The Joy of Cooking.'",
                            FullName = "Irma S. Rombauer"
                        },
                        new
                        {
                            Id = 28,
                            DateOfBirth = new DateOnly(1979, 11, 7),
                            Description = "American chef and author of 'Salt, Fat, Acid, Heat.'",
                            FullName = "Samin Nosrat"
                        },
                        new
                        {
                            Id = 29,
                            DateOfBirth = new DateOnly(1954, 4, 12),
                            Description = "American author, known for 'Into the Wild.'",
                            FullName = "Jon Krakauer"
                        },
                        new
                        {
                            Id = 30,
                            DateOfBirth = new DateOnly(1962, 10, 26),
                            Description = "American author, known for 'The Geography of Bliss.'",
                            FullName = "Eric Weiner"
                        },
                        new
                        {
                            Id = 31,
                            DateOfBirth = new DateOnly(1965, 7, 20),
                            Description = "British author, known for the 'Harry Potter' series.",
                            FullName = "J.K. Rowling"
                        },
                        new
                        {
                            Id = 32,
                            DateOfBirth = new DateOnly(1928, 6, 10),
                            Description = "American author of children's books, known for 'Where the Wild Things Are.'",
                            FullName = "Maurice Sendak"
                        },
                        new
                        {
                            Id = 33,
                            DateOfBirth = new DateOnly(1892, 1, 3),
                            Description = "English author, known for 'The Hobbit.'",
                            FullName = "J.R.R. Tolkien"
                        },
                        new
                        {
                            Id = 34,
                            DateOfBirth = new DateOnly(1973, 6, 6),
                            Description = "American author, known for 'The Name of the Wind.'",
                            FullName = "Patrick Rothfuss"
                        },
                        new
                        {
                            Id = 35,
                            DateOfBirth = new DateOnly(1920, 10, 8),
                            Description = "American science fiction author, known for 'Dune.'",
                            FullName = "Frank Herbert"
                        },
                        new
                        {
                            Id = 36,
                            DateOfBirth = new DateOnly(1948, 3, 17),
                            Description = "American-Canadian author, known for 'Neuromancer.'",
                            FullName = "William Gibson"
                        },
                        new
                        {
                            Id = 37,
                            DateOfBirth = new DateOnly(1954, 8, 15),
                            Description = "Swedish author, known for 'The Girl with the Dragon Tattoo.'",
                            FullName = "Stieg Larsson"
                        },
                        new
                        {
                            Id = 38,
                            DateOfBirth = new DateOnly(1971, 2, 24),
                            Description = "American author, known for 'Gone Girl.'",
                            FullName = "Gillian Flynn"
                        },
                        new
                        {
                            Id = 39,
                            DateOfBirth = new DateOnly(1968, 11, 22),
                            Description = "Cypriot-British author, known for 'The Silent Patient.'",
                            FullName = "Alex Michaelides"
                        },
                        new
                        {
                            Id = 40,
                            DateOfBirth = new DateOnly(1972, 8, 26),
                            Description = "British author, known for 'The Girl on the Train.'",
                            FullName = "Paula Hawkins"
                        },
                        new
                        {
                            Id = 41,
                            DateOfBirth = new DateOnly(1920, 8, 22),
                            Description = "American author, known for 'Fahrenheit 451.'",
                            FullName = "Ray Bradbury"
                        },
                        new
                        {
                            Id = 42,
                            DateOfBirth = new DateOnly(1903, 6, 25),
                            Description = "British author, known for '1984.'",
                            FullName = "George Orwell"
                        },
                        new
                        {
                            Id = 43,
                            DateOfBirth = new DateOnly(1894, 7, 26),
                            Description = "English author, known for 'Brave New World.'",
                            FullName = "Aldous Huxley"
                        },
                        new
                        {
                            Id = 44,
                            DateOfBirth = new DateOnly(1939, 11, 18),
                            Description = "Canadian author, known for 'The Handmaid's Tale.'",
                            FullName = "Margaret Atwood"
                        },
                        new
                        {
                            Id = 45,
                            DateOfBirth = new DateOnly(1919, 1, 1),
                            Description = "American author, known for 'The Catcher in the Rye.'",
                            FullName = "J.D. Salinger"
                        },
                        new
                        {
                            Id = 46,
                            DateOfBirth = new DateOnly(1950, 7, 22),
                            Description = "American author, known for 'The Outsiders.'",
                            FullName = "S.E. Hinton"
                        },
                        new
                        {
                            Id = 47,
                            DateOfBirth = new DateOnly(1854, 10, 16),
                            Description = "Irish author, known for 'The Picture of Dorian Gray.'",
                            FullName = "Oscar Wilde"
                        },
                        new
                        {
                            Id = 48,
                            DateOfBirth = new DateOnly(1797, 8, 20),
                            Description = "English author, known for 'Frankenstein.'",
                            FullName = "Mary Shelley"
                        },
                        new
                        {
                            Id = 49,
                            DateOfBirth = new DateOnly(1847, 11, 8),
                            Description = "Irish author, known for 'Dracula.'",
                            FullName = "Bram Stoker"
                        },
                        new
                        {
                            Id = 50,
                            DateOfBirth = new DateOnly(1821, 11, 11),
                            Description = "Russian author, known for 'Crime and Punishment.'",
                            FullName = "Fyodor Dostoevsky"
                        });
                });

            modelBuilder.Entity("LMS.DAL.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActivationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActivationUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertedUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("LMS.DAL.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActivationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActivationUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InsertedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertedUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("LMS.DAL.TrendingBook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("BorrowCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("TrendingBooks");
                });

            modelBuilder.Entity("LMS.DAL.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActivationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActivationUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("InsertedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertedUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LMS.DAL.Book", b =>
                {
                    b.HasOne("LMS.DAL.Data.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.DAL.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LMS.DAL.Feedback", b =>
                {
                    b.HasOne("LMS.DAL.Book", "Book")
                        .WithMany("Feedbacks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.DAL.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.DAL.Transaction", b =>
                {
                    b.HasOne("LMS.DAL.Book", "Book")
                        .WithMany("Transactions")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.DAL.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.DAL.TrendingBook", b =>
                {
                    b.HasOne("LMS.DAL.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LMS.DAL.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LMS.DAL.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.DAL.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LMS.DAL.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LMS.DAL.Book", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("LMS.DAL.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LMS.DAL.Data.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LMS.DAL.User", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
